### ISSUE TITLE
Capacitor C1 burns when I switched the Power On

### ISSUE THREAD

**Issue by AbidHussain70** [RobertGawron/SemiconductorRadioactivityDetector#41]

**Comment by RobertGawron** [comment]
@AbidHussain70: could you please say what the problem was? You closed the issue so I think you resolved it by yourself, the info about issue would be good for me and maybe other people who try to build the same device.

**Comment by AbidHussain70** [comment]
I made a new PCB. When I receive the PCB I will solder the components and will update.

**Comment by AbidHussain70** [comment]
Hi,
I made a new PCB and I solder the components, I am getting almost 2.4 V in the photo-diode, and almost 3.6 V across C4 capacitor, when I switched On the power. But after sometime the voltage across C4 jumps to 5 V and the voltage the photo-diode  terminal goes under 1 V. These are measurement without attaching photo-diodes to the terminal. 
What should be the voltage across the photo-diode terminal? And does the voltage of the C4 varies with the load? (I mean if I attached the photo-diodes).

**Comment by AbidHussain70** [comment]
I attached the photo-diodes and now the voltage across photo-diode is 2.5 V.

**Comment by RobertGawron** [comment]
@AbidHussain70: 
>What should be the voltage across the photo-diode terminal? 
By "terminal" you mean + input of operation amplifier (I mean pin 3 of U1)? If yes, then + and - pins have the same voltage measured to ground and - pin has voltage created by voltage divider R1+R2 = half of the power supply voltage. 

>And does the voltage of the C4 varies with the load? (I mean if I attached the photo-diodes).
The voltage will be always the same - it should be -4x12V (measured on pins of C4)

1. What is the voltage on pin 3 of the U1?
2. What's the voltage on pin 2 of U1?

**Comment by AbidHussain70** [comment]
By terminal I mean the input voltage for photo-diodes. 

![photodiode-github](https://user-images.githubusercontent.com/23444211/81783041-5e840a00-952d-11ea-951d-b13243965edd.JPG)


I made a small socket for Photo-diodes, and placed a connector on main board. The socket will be installed on the `connector.

`
![socket-photodiode](https://user-images.githubusercontent.com/23444211/81783109-752a6100-952d-11ea-987c-ccf287b552d2.jpg)

**Comment by RobertGawron** [comment]
@AbidHussain70: I see you created your own PCB and modified a a bit schematic.

![circuit](https://user-images.githubusercontent.com/169230/82575012-32e5cd00-9b88-11ea-9e76-e468abfb74d2.png)

What is the purpose of D1-D4 and are they connected in correct polarization? Can you check if voltage on terminal (I marked is as 1) is roughly -4x12V?
